### ISSUE TITLE
mode-mouse deprecated as of tmux v2.1

### ISSUE THREAD

**Issue by olalonde** [tangledhelix/dotfiles#3]
See https://github.com/tmux/tmux/blob/310f0a960ca64fa3809545badc629c0c166c6cd2/CHANGES#L6

https://github.com/tangledhelix/dotfiles/blob/master/tmux.conf#L130

should be replaced with `set -g mouse on`. Scrolling doesn't appear to be working anymore unfortunately. See https://github.com/tmux/tmux/issues/145

Current workaround:

`bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"`

**Comment by dzlab** [comment]
@olalonde zsh does not find command `bind', does the binding need to be added to `.tmux.conf`?

**Comment by tangledhelix** [comment]
@dzlab Yes, the bind is a tmux command, not zsh.

@olalonde I will update my tmux.conf soon, but I need to upgrade tmux on a few systems I personally use before I can do so or I'll break my own environment. I use a bunch of RHEL/CentOS systems and will probably have to roll my own RPMs, as they are perennially behind on updates...

**Comment by marcodejongh** [comment]
@olalonde :+1: thx for the workaround

**Comment by tangledhelix** [comment]
I think this is fixed... the current test works whether your shell is bash or zsh, so far as I can tell. Not tested in a situation where *csh is used by tmux. And I believe the test should continue to work in the future, not breaking again when we reach 2.2.
